<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <PackageId>BergamotTranslatorSharp.REDox.MessagePack</PackageId>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CAPCOM.REDox.MessagePack" />
    <ProjectReference Include="..\BergamotTranslatorSharp.REDox\BergamotTranslatorSharp.REDox.csproj" />
  </ItemGroup>
</Project>
