name: Package

on:
  workflow_dispatch: 
  push:
    branches: [master]
    tags: [v*.*.*]
  pull_request:
    branches: ["**"]

jobs:
  win:
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: x64
            runner: windows-latest
            artifact: libs-win-x64
            build_dir: build
            vcpkg_cache_prefix: vcpkg-windows-x64-content
            ccache_cache_prefix: ccache-windows-x64
            configure_args: >-
              -S . -B build
              -DBUILD_ARCH=corei7-avx
              -DCMAKE_BUILD_TYPE=Release
              -DUSE_STATIC_LIBS=ON
              '-DCMAKE_POLICY_VERSION_MINIMUM=3.5'
              -DVCPKG_TARGET_TRIPLET=x64-windows-static
              -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake
          - arch: x86
            runner: windows-latest
            artifact: libs-win-x86
            build_dir: build
            vcpkg_cache_prefix: vcpkg-windows-x86-content
            ccache_cache_prefix: ccache-windows-x86
            configure_args: >-
              -S . -B build -A Win32
              -DCMAKE_BUILD_TYPE=Release
              -DUSE_STATIC_LIBS=ON
              '-DCMAKE_POLICY_VERSION_MINIMUM=3.5'
              -DVCPKG_TARGET_TRIPLET=x86-windows-static
              -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake
          - arch: arm64
            runner: windows-11-arm
            artifact: libs-win-arm64
            build_dir: out/build/windows-arm64-clangcl-release
            vcpkg_cache_prefix: vcpkg-windows-arm64
            ccache_cache_prefix: ccache-windows-arm64
            configure_args: >-
              --preset windows-arm64-clangcl-release
    runs-on: ${{ matrix.runner }}
    name: Build Windows ${{ matrix.arch }} Native Lib
    env:
      CCACHE_BASEDIR: "${{ github.workspace }}"
      CCACHE_DIR: "${{ github.workspace }}\\ccache"
      CCACHE_COMPILERCHECK: content
      CCACHE_COMPRESS: "true"
      CCACHE_COMPRESSLEVEL: 9
      CCACHE_MAXSIZE: 200M
      CCACHE_VERSION: "4.5"
      VCPKG_DEFAULT_BINARY_CACHE: "${{ github.workspace }}\\vcpkg\\"
      VCPKG_ROOT: C:\vcpkg
      CCACHE_CMAKE_ARGS: -DCMAKE_CXX_COMPILER_LAUNCHER=${{ github.workspace }}\ccache.exe -DCMAKE_C_COMPILER_LAUNCHER=${{ github.workspace }}\ccache.exe
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Download ccache
        shell: cmake -P {0}
        run: |
          set(ccache_url "https://github.com/cristianadam/ccache/releases/download/v${{ env.CCACHE_VERSION }}/${{ runner.os }}.tar.xz")
          file(DOWNLOAD "${ccache_url}" ./ccache.tar.xz SHOW_PROGRESS)
          execute_process(COMMAND ${CMAKE_COMMAND} -E tar xvf ./ccache.tar.xz RESULT_VARIABLE ret)
          if(ret AND NOT ret EQUAL 0)
            message( FATAL_ERROR "Bad exit status")
          endif()

      - name: Generate cache key
        id: cache_vars
        shell: powershell
        run: |
          "timestamp=$(Get-Date -Format 'yyyy-MM-ddTHH.mm.ss')" >> $env:GITHUB_OUTPUT

      - name: Cache-op for build-cache through ccache
        uses: actions/cache@v4
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ${{ matrix.ccache_cache_prefix }}-${{ env.CCACHE_COMPILERCHECK }}-${{ github.ref }}-${{ steps.cache_vars.outputs.timestamp }}
          restore-keys: |-
            ${{ matrix.ccache_cache_prefix }}-${{ env.CCACHE_COMPILERCHECK }}-${{ github.ref }}
            ${{ matrix.ccache_cache_prefix }}-${{ env.CCACHE_COMPILERCHECK }}
            ${{ matrix.ccache_cache_prefix }}

      - name: Cache-op for build-cache through vcpkg
        uses: actions/cache@v4
        with:
          path: ${{ env.VCPKG_DEFAULT_BINARY_CACHE }}
          key: ${{ matrix.vcpkg_cache_prefix }}-${{ github.ref }}-${{ steps.cache_vars.outputs.timestamp }}
          restore-keys: |-
            ${{ matrix.vcpkg_cache_prefix }}-${{ github.ref }}
            ${{ matrix.vcpkg_cache_prefix }}

      - name: Create vcpkg cache directory
        shell: powershell
        run: |
          New-Item -ItemType Directory -Force -Path "${{ env.VCPKG_DEFAULT_BINARY_CACHE }}" | Out-Null

      - name: ccache prolog
        run: |-
          ${{github.workspace}}\ccache.exe -sv # Print current cache stats
          ${{github.workspace}}\ccache.exe -z # Print current cache stats

      - name: Add Visual Studio tools to PATH
        if: ${{ matrix.arch == 'arm64' }}
        shell: powershell
        run: |
          $vswhere = Join-Path ${env:ProgramFiles(x86)} "Microsoft Visual Studio\Installer\vswhere.exe"
          $vsPath = & $vswhere -latest -products * -property installationPath
          $ninja = Join-Path $vsPath "Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja\ninja.exe"
          if (!(Test-Path $ninja)) {
            throw "Ninja was not found at $ninja"
          }
          $clangCl = Join-Path $vsPath "VC\Tools\Llvm\ARM64\bin\clang-cl.exe"
          if (!(Test-Path $clangCl)) {
            throw "ARM64 clang-cl was not found at $clangCl"
          }
          Split-Path -Parent $ninja | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          Split-Path -Parent $clangCl | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          & $ninja --version
          & $clangCl --version

      - name: Configure
        run: cmake ${{ matrix.configure_args }} ${{ env.CCACHE_CMAKE_ARGS }}
        shell: powershell

      - name: Build
        run: cmake --build ${{ matrix.build_dir }} --config Release -j3 --target bergamot_translator_dynamic
        shell: powershell

      - name: Install
        run: cmake --install ${{ matrix.build_dir }} --prefix libs --component bergamot_translator_dynamic
        shell: powershell

      - name: ccache epilog
        run: |-
          ${{github.workspace}}\\ccache.exe -sv # Print current cache stats

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact }}
          path: libs/*

  linux:
    runs-on: ${{ matrix.runner }}
    name: Build Linux ${{ matrix.arch }} Native Lib
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: x64
            runner: ubuntu-latest
            use_mkl: true
            artifact: libs-linux-x64
          - arch: arm64
            runner: ubuntu-24.04-arm
            use_mkl: false
            artifact: libs-linux-arm64
    env:
      ccache_basedir: ${{ github.workspace }}
      ccache_dir: "${{ github.workspace }}/.ccache"
      ccache_compilercheck: content
      ccache_compress: 'true'
      ccache_compresslevel: 9
      ccache_maxsize: 200M
      ccache_cmake: -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_C_COMPILER_LAUNCHER=ccache
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install Dependencies
        run: |-
          sudo apt-get update
          sudo apt-get install -y libprotobuf-dev protobuf-compiler libboost-all-dev ccache ninja-build libunwind-dev
      - name: Install MKL
        if: matrix.use_mkl
        run: |-
          wget -qO- "https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB" | sudo apt-key add -
          sudo sh -c "echo deb https://apt.repos.intel.com/mkl all main > /etc/apt/sources.list.d/intel-mkl.list"
          sudo apt-get update -o Dir::Etc::sourcelist="/etc/apt/sources.list.d/intel-mkl.list"
          sudo apt-get install -y --no-install-recommends intel-mkl-64bit-2020.0-088
      - name: Generate ccache_vars for ccache based on machine
        shell: bash
        id: ccache_vars
        run: |-
          echo "hash=$(echo ${{ env.ccache_compilercheck }})" >> $GITHUB_OUTPUT
          echo "timestamp=$(date '+%Y-%m-%dT%H.%M.%S')" >> $GITHUB_OUTPUT
      - name: Cache-op for build-cache through ccache
        uses: actions/cache@v4
        with:
          path: ${{ env.ccache_dir }}
          key: ccache-linux-${{ matrix.arch }}-${{ steps.ccache_vars.outputs.hash }}-${{ github.ref }}-${{ steps.ccache_vars.outputs.timestamp }}
          restore-keys: |-
            ccache-linux-${{ matrix.arch }}-${{ steps.ccache_vars.outputs.hash }}-${{ github.ref }}
            ccache-linux-${{ matrix.arch }}-${{ steps.ccache_vars.outputs.hash }}
            ccache-linux-${{ matrix.arch }}
      - name: ccache environment setup
        run: |-
          echo "CCACHE_COMPILER_CHECK=${{ env.ccache_compilercheck }}" >> $GITHUB_ENV
          echo "CCACHE_BASEDIR=${{ env.ccache_basedir }}" >> $GITHUB_ENV
          echo "CCACHE_COMPRESS=${{ env.ccache_compress }}" >> $GITHUB_ENV
          echo "CCACHE_COMPRESSLEVEL=${{ env.ccache_compresslevel }}" >> $GITHUB_ENV
          echo "CCACHE_DIR=${{ env.ccache_dir }}" >> $GITHUB_ENV
          echo "CCACHE_MAXSIZE=${{ env.ccache_maxsize }}" >> $GITHUB_ENV
      - name: ccache prolog
        run: |-
          ccache -s # Print current cache stats
          ccache -z # Zero cache entry
      - name: Configure
        run: |-
          cmake -S . -B build -G Ninja \
            ${{ env.ccache_cmake }} \
            -DCMAKE_BUILD_TYPE=Release \
            -DUSE_STATIC_LIBS=ON \
            -DUSE_MKL=${{ matrix.use_mkl }} \
            -DBUILD_ARCH=native \
            -DSSPLIT_USE_INTERNAL_PCRE2=ON \
            -DGIT_SUBMODULE=OFF
      - name: Build
        run: cmake --build build --config Release -j3 --target bergamot_translator_dynamic
      - name: Install
        run: cmake --install build --prefix libs --component bergamot_translator_dynamic
      - name: ccache epilog
        run: 'ccache -s # Print current cache stats'
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact }}
          path: libs/*

  macos:
    runs-on: ${{ matrix.runner }}
    name: Build macOS ${{ matrix.arch }} Native Lib
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: arm64
            runner: macos-latest
            artifact: libs-macos-arm64
          - arch: x64
            runner: macos-13
            artifact: libs-macos-x64
    env:
      ccache_basedir: ${{ github.workspace }}
      ccache_dir: "${{ github.workspace }}/.ccache"
      ccache_compilercheck: content
      ccache_compress: 'true'
      ccache_compresslevel: 9
      ccache_maxsize: 200M
      ccache_cmake: -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_C_COMPILER_LAUNCHER=ccache
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install Dependencies
        run: |-
          brew install ccache protobuf boost cmake llvm@18 gperftools
      - name: Generate ccache_vars for ccache based on machine
        shell: bash
        id: ccache_vars
        run: |-
          echo "hash=$(echo ${{ env.ccache_compilercheck }})" >> $GITHUB_OUTPUT
          echo "timestamp=$(date '+%Y-%m-%dT%H.%M.%S')" >> $GITHUB_OUTPUT
      - name: Cache-op for build-cache through ccache
        uses: actions/cache@v4
        with:
          path: ${{ env.ccache_dir }}
          key: ccache-macos-${{ matrix.arch }}-${{ steps.ccache_vars.outputs.hash }}-${{ github.ref }}-${{ steps.ccache_vars.outputs.timestamp }}
          restore-keys: |-
            ccache-macos-${{ matrix.arch }}-${{ steps.ccache_vars.outputs.hash }}-${{ github.ref }}
            ccache-macos-${{ matrix.arch }}-${{ steps.ccache_vars.outputs.hash }}
            ccache-macos-${{ matrix.arch }}
      - name: ccache environment setup
        run: |-
          echo "CCACHE_COMPILER_CHECK=${{ env.ccache_compilercheck }}" >> $GITHUB_ENV
          echo "CCACHE_BASEDIR=${{ env.ccache_basedir }}" >> $GITHUB_ENV
          echo "CCACHE_COMPRESS=${{ env.ccache_compress }}" >> $GITHUB_ENV
          echo "CCACHE_COMPRESSLEVEL=${{ env.ccache_compresslevel }}" >> $GITHUB_ENV
          echo "CCACHE_DIR=${{ env.ccache_dir }}" >> $GITHUB_ENV
          echo "CCACHE_MAXSIZE=${{ env.ccache_maxsize }}" >> $GITHUB_ENV
      - name: ccache prolog
        run: |-
          ccache -s # Print current cache stats
          ccache -z # Zero cache entry
      - name: cmake
        run: |-
          LLVM_PREFIX="$(brew --prefix llvm@18)"
          GPERFTOOLS_PREFIX="$(brew --prefix gperftools)"
          mkdir -p build
          cd build
          cmake -L .. ${{ env.ccache_cmake }} \
            -DCMAKE_C_COMPILER="$LLVM_PREFIX/bin/clang" \
            -DCMAKE_CXX_COMPILER="$LLVM_PREFIX/bin/clang++" \
            -DGPERFTOOLS_ROOT="$GPERFTOOLS_PREFIX" \
            -DCMAKE_BUILD_TYPE=Release \
            -DUSE_STATIC_LIBS=ON \
            -DCMAKE_POLICY_VERSION_MINIMUM=3.5 \
            -DGIT_SUBMODULE=OFF
      - name: Build from source
        working-directory: build
        run: cmake --build . --config Release -j3 --target bergamot_translator_dynamic
      - name: Install
        working-directory: build
        run: cmake --install . --prefix "../libs" --component bergamot_translator_dynamic
      - name: ccache epilog
        run: 'ccache -s # Print current cache stats'
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact }}
          path: libs/*

  dotnet:
    runs-on: ubuntu-latest
    name: Build .NET Lib
    needs:
      - win
      - linux
      - macos
    permissions:
      contents: write
      packages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - uses: gittools/actions/gitversion/setup@v3.1.11
        with:
          versionSpec: "5.x"
      - id: gitversion
        uses: gittools/actions/gitversion/execute@v3.1.11
      - uses: actions/download-artifact@v4
        with:
          path: libs
          merge-multiple: true
      - run: |
          dotnet pack BergamotTranslatorSharp -c Release -o pack \
            -p:Version=${{ steps.gitversion.outputs.fullSemVer }} \
            -p:AssemblyVersion=${{ steps.gitversion.outputs.assemblySemVer }} \
            -p:FileVersion=${{ steps.gitversion.outputs.assemblySemFileVer }} \
            -p:InformationalVersion=${{ steps.gitversion.outputs.informationalVersion }}
      - uses: actions/upload-artifact@v4
        with:
          name: nupkg
          path: pack/*

      # 1. Publish to GitHub Packages Registry (always runs & uses repository token)
      - name: Push to GitHub Packages
        run: |
          dotnet nuget add source --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text-config --name github "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"
          dotnet nuget push pack/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source github --skip-duplicate

      # 2. Try pushing to NuGet.org (won't stop the workflow if it fails)
      - name: NuGet login
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        id: nuget_login
        continue-on-error: true
        uses: NuGet/login@v1
        with:
          user: Freesia

      - name: NuGet push
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        continue-on-error: true
        run: dotnet nuget push pack/*.nupkg --api-key ${{ steps.nuget_login.outputs.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate

      # 3. Create GitHub Release on Tag
      - if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: softprops/action-gh-release@v2
        with:
          files: pack/*.nupkg
          generate_release_notes: true
          draft: false
          prerelease: false
